services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: ""
    startCommand: python server.py
    autoDeploy: true
buildCommand: pip install -r requirements.txt
environment:
  pythonVersion: 3.10.13
