services:
  - type: web
    name: my-backend-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    buildCommand: pip install --upgrade pip
    startCommand: python server.py
    environment:
      pythonVersion: 3.12.4
